---
username:
  description: "The Username for ansible."
  type: "string"
  secret: true
  required: true
passwort:
  description: >-
    Passwort of Ansible User.
  type: "string"
  required: true
  secret: true
hostname:
  description: >-
    Url to Ansible Instance.
  type: "string"
  required: true
